/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package no.nav.kafkaconnect;

import no.nav.kafkaconnect.sink.JdbcSinkConfig;
import no.nav.kafkaconnect.sink.NadaJdbcSinkTask;
import org.apache.kafka.common.config.Config;
import org.apache.kafka.common.config.ConfigDef;
import org.apache.kafka.connect.connector.Task;
import org.apache.kafka.connect.sink.SinkConnector;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public class NadaJdbcSinkConnector extends SinkConnector {
    private static final Logger log = LoggerFactory.getLogger(NadaJdbcSinkConnector.class);

    private Map<String, String> configProps;

    public Class<? extends Task> taskClass() {
        return NadaJdbcSinkTask.class;
    }

    @Override
    public List<Map<String, String>> taskConfigs(int maxTasks) {
        log.info("Setting task configurations for {} workers.", maxTasks);
        final List<Map<String, String>> configs = new ArrayList<>(maxTasks);
        for (int i = 0; i < maxTasks; ++i) {
            configs.add(configProps);
        }
        return configs;
    }

    @Override
    public void start(Map<String, String> props) {
        configProps = props;
    }

    @Override
    public void stop() {
    }

    @Override
    public ConfigDef config() {
        return JdbcSinkConfig.CONFIG_DEF;
    }

    @Override
    public Config validate(Map<String, String> connectorConfigs) {
        // TODO cross-fields validation here: pkFields against the pkMode
        return super.validate(connectorConfigs);
    }

    @Override
    public String version() {
        return "0.0.1";
    }
}
